CREATE TABLE TB_JOB (
                        ID           NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        NAME         VARCHAR2(100 CHAR)  NOT NULL,
                        DESCRIPTION  VARCHAR2(1000 CHAR),

                        CRON_EXPR    VARCHAR2(256 CHAR)  NOT NULL,

                        NEXT_DUE_AT  TIMESTAMP(6)        NOT NULL,  -- 스케줄 커서
                        LEASE_UNTIL  TIMESTAMP(6),                  -- 선점 가시성(옵션)

                        ENABLED      CHAR(1)             DEFAULT 'Y' NOT NULL
                            CHECK (ENABLED IN ('Y','N')),

                        CREATED_AT   TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        UPDATED_AT   TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 업무상 유니크 이름
CREATE UNIQUE INDEX UQ_TB_JOB_NAME ON TB_JOB (NAME);

-- 듀 스캔 최적화 (킬스위치 + 커서)
CREATE INDEX IX_TB_JOB_DUE ON TB_JOB (ENABLED, NEXT_DUE_AT);
