CREATE TABLE TB_TASK_DEP (
                             PRE_TASK_ID  NUMBER(19,0) NOT NULL,
                             POST_TASK_ID NUMBER(19,0) NOT NULL,
                             CREATED_AT   TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

                             CONSTRAINT FK_DEP_PRE  FOREIGN KEY (PRE_TASK_ID)  REFERENCES TB_TASK(ID),
                             CONSTRAINT FK_DEP_POST FOREIGN KEY (POST_TASK_ID) REFERENCES TB_TASK(ID),
                             CONSTRAINT UX_TASK_DEP_UNIQ UNIQUE (PRE_TASK_ID, POST_TASK_ID)
);

CREATE INDEX IX_TASK_DEP_POST ON TB_TASK_DEP (POST_TASK_ID);
CREATE INDEX IX_TASK_DEP_PRE  ON TB_TASK_DEP (PRE_TASK_ID);
