CREATE TABLE TB_TASK_RUN (
                             ID           NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             JOB_RUN_ID   NUMBER(19,0) NOT NULL,
                             TASK_ID      NUMBER(19,0) NOT NULL,

                             STATUS       VARCHAR2(20 CHAR) NOT NULL
                                 CHECK (STATUS IN ('BLOCKED','READY','RUNNING','DONE','FAILED','SKIPPED','CANCELLED','EXPIRED')),

                             ATTEMPT      NUMBER(10,0) DEFAULT 1 NOT NULL,
                             PRE_CNT      NUMBER(10,0) DEFAULT 0 NOT NULL,
                             DONE_CNT     NUMBER(10,0) DEFAULT 0 NOT NULL,

                             WORKER_ID    NUMBER(10,0),

                             AVAILABLE_AT TIMESTAMP(6),
                             LEASE_UNTIL  TIMESTAMP(6),

                             STARTED_AT   TIMESTAMP(6) WITH LOCAL TIME ZONE,
                             FINISHED_AT  TIMESTAMP(6) WITH LOCAL TIME ZONE,

                             CREATED_AT   TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             UPDATED_AT   TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

                             LAST_ERROR   VARCHAR2(2000 CHAR),

                             CONSTRAINT FK_TASK_RUN_JOB_RUN FOREIGN KEY (JOB_RUN_ID) REFERENCES TB_JOB_RUN(ID),
                             CONSTRAINT FK_TASK_RUN_TASK    FOREIGN KEY (TASK_ID)    REFERENCES TB_TASK(ID),
                             CONSTRAINT UX_TASK_RUN UNIQUE (JOB_RUN_ID, TASK_ID, ATTEMPT)
);

-- 스캔/클레임/모니터링 최적화
CREATE INDEX IX_TASK_RUN_READY   ON TB_TASK_RUN (STATUS, AVAILABLE_AT);
CREATE INDEX IX_TASK_RUN_LEASE   ON TB_TASK_RUN (LEASE_UNTIL);
CREATE INDEX IX_TASK_RUN_JOBTASK ON TB_TASK_RUN (JOB_RUN_ID, TASK_ID);
