spring:
  datasource:
    url: ${ORACLE_CONN}
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  flyway:
    enabled: true
    locations: classpath:db/migration/oracle   # ← adapter-jdbc JAR 내부 리소스 사용

majide:
  zone: Asia/Seoul
  scheduler:
    enabled: true
    tick-delay-ms: 3000
    maintenance-delay-ms: 10000
    job-lease: PT5S
    task-lease: PT30S
    max-claims: 10
    retry-backoff: PT10S
    finished-ttl: P30D

  catalog:
    jobs:
      - name: "PCF Calc Pipeline"
        description: "OEM PCF 파이프라인"
        cronExpr: "0 0/2 * * * ?"     # Quartz 6필드: 2분마다
        tasks:
          - name: orders.sync
            handler: orders.sync
          - name: orders.enrich
            handler: orders.enrich
            dependsOn: [ "orders.sync" ]
          - name: orders.publish
            handler: orders.publish
            dependsOn: [ "orders.enrich" ]